### ISSUE TITLE
Unterstützung für eltako_dimmer  

### ISSUE THREAD

**Issue by brunok21** [awaescher/homebridge-eltako-minisafe2#1]
Moin ich habe das Plugin installiert,

ich konnte es verbinden, zumindest zeigt er in der Homebridge alles grün an.
Ich habe auch den QR Code scannen können.

Aber ich bekomme diese Meldung als Dauerschleife.
[12/25/2023, 4:07:31 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 14EB) is running on port 51067.
[12/25/2023, 4:07:32 PM] [homebridge-eltako-minisafe2] Launched child bridge with PID 1397
[12/25/2023, 4:07:32 PM] Registering platform 'homebridge-eltako-minisafe2.Homebridge Eltako for MiniSafe2'
[12/25/2023, 4:07:32 PM] [homebridge-eltako-minisafe2] Loaded homebridge-eltako-minisafe2 v2.0.6 child bridge successfully
[12/25/2023, 4:07:32 PM] Loaded 0 cached accessories from cachedAccessories.0EEE2FBC1C2B.
[12/25/2023, 4:07:32 PM] [homebridge-eltako-minisafe2] Connecting to Eltako MiniSafe2 on 192.168.31.241
[12/25/2023, 4:07:32 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:32 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-eltako-minisafe2) is running on port 30315.
[12/25/2023, 4:07:32 PM] [homebridge-eltako-minisafe2] newDevices is not iterable
[12/25/2023, 4:07:34 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:34 PM] [homebridge-eltako-minisafe2] newDevices is not iterable
[12/25/2023, 4:07:36 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:36 PM] [homebridge-eltako-minisafe2] newDevices is not iterable
[12/25/2023, 4:07:38 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:38 PM] [homebridge-eltako-minisafe2] newDevices is not iterable
[12/25/2023, 4:07:40 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:40 PM] [homebridge-eltako-minisafe2] newDevices is not iterable
[12/25/2023, 4:07:42 PM] [homebridge-eltako-minisafe2] Updating device state cache ...
[12/25/2023, 4:07:42 PM] [homebridge-eltako-minisafe2] newDevices is not iterable

* **Plugin Version**:2.0.6

OS | Ubuntu Focal Fossa (20.04.5 LTS)
192.168.31.105
2a01:41e1:6301:f600:215:5dff:fe1f:7801
homebridge-vm
root
Node.js Version v20.10.0
/opt/homebridge/bin
/var/lib/homebridge
/var/lib/homebridge/config.json
/var/lib/homebridge/node_modules
GMT+0100
Ja

</body>
</html>

**Comment by awaescher** [comment]
Hi. Kannst du deine Geräte in der Eltako GFA5-App sehen und steuern?

**Comment by brunok21** [comment]
ja das funktioniert ohne Probleme.
Auch über Alexa funktioniert das.

**Comment by brunok21** [comment]
Ich habe es hinbekommen. Alles neu aufgesetzt. Jetzt sind die Rollos da aber die Lampen können nicht bedient werden.
Ist das normal? Im homekit steht, dass die nicht unterstützt werden.
In der homebridge werden die gar nicht angezeigt.

**Comment by awaescher** [comment]
Alles neu aufgesetzt? Wie das?

Wenn du die GFA-App verwenden kannst, stell sicher, dass deine Konfiguration der App in der App unter Einstellungen auf den Controller (Minisafe2) gespeichert ist. Das was der Controller an Geräten zurückgibt, kann das Plugin in HomeKit veröffentlichen.

Dass Geräte nicht gesteuert werden können ist nicht normal, nein. Vermutlich sind deine Geräte anders konfiguriert als die von mir soweit analysierten.

Kannst du vielleicht mal die folgenden Dateien auslesen und mir irgendwie zukommen lassen? Aber bitte achte darauf, dass keine Passwörter enthalten sind.
``` sql
--     XXX.XXX.XXX.XXX ist die IP-Adresse des MiniSafe2
http://XXX.XXX.XXX.XXX/file/config/iqpro/systems.json?at=ACCESSTOKEN
http://XXX.XXX.XXX.XXX/file/config/iqpro/config.json?at=ACCESSTOKEN
http://XXX.XXX.XXX.XXX/cmd?XC_FNC=GetStates&at=ACCESSTOKEN
```

Wenn du statt einem AccessToken ein Passwort verwenden willst, musst du anstelle von `at` das Argument `XC_PASS` verwenden:

``` sql
--     XXX.XXX.XXX.XXX ist die IP-Adresse des MiniSafe2
http://XXX.XXX.XXX.XXX/file/config/iqpro/systems.json?XC_PASS=MYPASSWORD
http://XXX.XXX.XXX.XXX/file/config/iqpro/config.json?XC_PASS=MYPASSWORD
http://XXX.XXX.XXX.XXX/cmd?XC_FNC=GetStates&XC_PASS=MYPASSWORD
```

**Comment by brunok21** [comment]
Moin ich habe die Homebridge auf dem MiniPC neu installiert.
hier die config.jason

    "bridge": {
        "name": "Homebridge 14EB",
        "username": "0E:75:5A:2A:14:EB",
        "port": 51067,
        "pin": "359-27-883",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "ip": "192.168.31.241",
            "password": "meinpasswort",
            "_bridge": {
                "username": "0E:EE:2F:BC:1C:2B",
                "port": 30315
            },
            "platform": "Homebridge Eltako for MiniSafe2"
        },
        {
            "watch": [
                "192.168.31.240"
            ],
            "_bridge": {
                "username": "0E:62:6D:BB:A1:1F",
                "port": 52496
            },
            "platform": "Shelly2PMPlus"
        },
        {
            "name": "Shelly",
            "admin": {
                "enabled": true
            },
            "platform": "Shelly",
            "_bridge": {
                "username": "0E:5E:C0:F2:69:4A",
                "port": 55703
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-shelly-2pm-plus",
        "homebridge-shelly"
    ]
}

**Comment by awaescher** [comment]
Das ist die Config der HomeBridge, die scheint okay zu sein. Kannst du bitte die Dateien des MiniSafe abrufen? Ich hab meinen vorigen Kommentar aktualisiert und die API-Endpunkte eingetragen. Wenn du einen AccessToken hast, kannst du den bei `at=` angeben. Wenn du das Passwort verwendest, musst du das mit `&XC_PASS=MeinKillerPasswort` angeben.

Wenn du mir die Daten privat zukommen lassen willst, findest du meine Email-Adresse in der Commit-History.

**Comment by brunok21** [comment]
Ok habe ich gemacht. Übrigens Frohe Weihnachten und vielen Dank für deinen Support.

{"XC_SUC":[{"type":"ENOCEAN","sid":"02","adr":"FFD74089","deviceProtocol":"normal","senderID":"FFC65098","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":false,"rv":25,"rt":25,"lock":false}},{"type":"ENOCEAN","sid":"01","adr":"00000001","deviceProtocol":"normal","senderID":"FFC65081","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":0,"pos":0,"sync":false,"rv":200,"rt":200,"lock":false}},{"type":"ENOCEAN","sid":"03","adr":"FFD7409E","deviceProtocol":"normal","senderID":"FFC65099","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"off","level":0,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"04","adr":"FFD7408D","deviceProtocol":"normal","senderID":"FFC6509A","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":99,"sync":true,"rv":25,"rt":25,"lock":false}},{"type":"ENOCEAN","sid":"05","adr":"FFD7408E","deviceProtocol":"normal","senderID":"FFC6509B","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":99,"sync":true,"rv":30,"rt":30,"lock":false}},{"type":"ENOCEAN","sid":"06","adr":"FFD7408F","deviceProtocol":"normal","senderID":"FFC6509C","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":25,"rt":28,"lock":false}},{"type":"ENOCEAN","sid":"07","adr":"FFD7408B","deviceProtocol":"normal","senderID":"FFC6509D","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":25,"rt":25,"lock":false}},{"type":"ENOCEAN","sid":"08","adr":"FFD7408A","deviceProtocol":"normal","senderID":"FFC6509E","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":false,"rv":15,"rt":15,"lock":false}},{"type":"ENOCEAN","sid":"09","adr":"FFD74087","deviceProtocol":"normal","senderID":"FFC6509F","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":false,"rv":15,"rt":15,"lock":false}},{"type":"ENOCEAN","sid":"0A","adr":"FFD74088","deviceProtocol":"normal","senderID":"FFC650A0","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":false,"rv":25,"rt":25,"lock":false}},{"type":"ENOCEAN","sid":"0B","adr":"FFD74085","deviceProtocol":"normal","senderID":"FFC650A1","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":200,"rt":200,"lock":false}},{"type":"ENOCEAN","sid":"0C","adr":"FFD74086","deviceProtocol":"normal","senderID":"FFC650A2","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":27,"rt":27,"lock":false}},{"type":"ENOCEAN","sid":"0D","adr":"FFD74083","deviceProtocol":"normal","senderID":"FFC650A3","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":false,"rv":27,"rt":27,"lock":false}},{"type":"ENOCEAN","sid":"0E","adr":"FFD74084","deviceProtocol":"normal","senderID":"FFC650A4","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":200,"rt":200,"lock":false}},{"type":"ENOCEAN","sid":"0F","adr":"FFD74081","deviceProtocol":"normal","senderID":"FFC650A5","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":200,"rt":200,"lock":false}},{"type":"ENOCEAN","sid":"10","adr":"FFD74082","deviceProtocol":"normal","senderID":"FFC650A6","virtual":false,"data":"eltako_blind","state":{"rssiPercentage":100,"pos":0,"sync":true,"rv":200,"rt":200,"lock":false}},{"type":"ENOCEAN","sid":"11","adr":"FFD7409F","deviceProtocol":"normal","senderID":"FFC650A7","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":0,"timeout":false,"state":null,"level":null,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"12","adr":"FFD740A0","deviceProtocol":"normal","senderID":"FFC650A8","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"on","level":100,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"13","adr":"FFD740A1","deviceProtocol":"normal","senderID":"FFC650A9","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":0,"timeout":false,"state":null,"level":null,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"14","adr":"FFD740A2","deviceProtocol":"normal","senderID":"FFC650AA","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":0,"timeout":false,"state":null,"level":null,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"15","adr":"FFD740A3","deviceProtocol":"normal","senderID":"FFC650AB","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"on","level":100,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"16","adr":"FFD740A4","deviceProtocol":"normal","senderID":"FFC650AC","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"on","level":100,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"17","adr":"FFD740A5","deviceProtocol":"normal","senderID":"FFC650AD","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"off","level":0,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"18","adr":"FFD740A6","deviceProtocol":"normal","senderID":"FFC650AE","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"off","level":0,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"19","adr":"FFD74091","deviceProtocol":"normal","senderID":"FFC650AF","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"off","level":0,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"1A","adr":"FFD74093","deviceProtocol":"normal","senderID":"FFC650B1","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":100,"timeout":false,"state":"off","level":0,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"1B","adr":"FFD74092","deviceProtocol":"normal","senderID":"FFC650B2","virtual":false,"data":"eltako_dimmer","state":{"rssiPercentage":0,"timeout":false,"state":null,"level":null,"ramp_time":0,"lock":false}},{"type":"ENOCEAN","sid":"1C","adr":"FFD74094","deviceProtocol":"normal","virtual":false,"data":"eltako_powermeter","state":{"rssiPercentage":100,"power":118.0,"energy":8196500.0,"energyNT":0.0,"ongoing_energy_usage":8196500.0}},{"type":"ENOCEAN","sid":"1D","adr":"059FAA83","deviceProtocol":"normal","senderID":"FFC65082","virtual":false,"data":"eltako_switch","state":{"rssiPercentage":0,"state":"off","lock":false}}]}

[config.json](https://github.com/awaescher/homebridge-eltako-minisafe2/files/13770747/config.json)
[systems.json](https://github.com/awaescher/homebridge-eltako-minisafe2/files/13770748/systems.json)

**Comment by awaescher** [comment]
Ich sehe gerade dass deine Lichter alle über Dimmer gesteuert werden:

```json
{
  "name": "Spots Couch",
  "info": {
    "data": "eltako_dimmer",  
    "vendor": "eltako",
    "_target": "light"
  },
},
```

[Dimmer sind noch nicht unterstützt](https://github.com/awaescher/homebridge-eltako-minisafe2?tab=readme-ov-file#supported-devices), da ich keine entsprechenden Testgeräte zur Verfügung habe. Das heißt, Eltako hat mir netterweise ein Dimmer zugeschickt, aber der ist noch nicht eingebaut und konfiguriert. Ich selbst benutze keine Eltako-Installation und muss nur meinem Bekannten gut zureden, die Testgeräte installieren zu lassen.

Dein Garagentor sollte allerdings als Schalter im HomeKit verfügbar sein, oder?

**Comment by awaescher** [comment]
Ich habe eben [eine Test-Version gepushed, die experimentellen Support für den Eltako-Dimmer](https://github.com/awaescher/homebridge-eltako-minisafe2/commit/5fd73f014e1fab8627555594de5ca09acb469346) mitbringt.
Da ich leider kein Testgerät habe, wäre ich für entsprechendes Feedback sehr dankbar.

**Comment by brunok21** [comment]
Ich habe das Update gemacht. Du bist ein Genie. Es funktioniert, auch mit Dimmer.

vielen Dank

**Comment by awaescher** [comment]
Das freut mich sehr. Die Helligkeitssteuerung funktioniert auch richtig? Bei den Jalousien musste ich die Prozentzahl umrechnen (30% bei Eltako = 70% in HomeKit).
Wenn ja, würdest du das Issue bitte schließen?

**Comment by awaescher** [comment]
Jemand da?

**Comment by awaescher** [comment]
Hast du mir noch ein Feedback zum vorigen Kommentar?

**Comment by brunok21** [comment]
Läuft alles, ich bin aber jetzt doch auf Home Assistent gewechselt, wegen dem Dashboard.

**Comment by awaescher** [comment]
Kein Ding. Kannst du mir sagen, ob die Helligkeit in Prozent richtig angezeigt war und eingestellt werden konnte?

**Comment by brunok21** [comment]
Ja hat alles richtig geklappt.

**Comment by awaescher** [comment]
Danke für dein Feedback
