### ISSUE TITLE
Eltako-FSR14 switches are not displayed in homebridge

### ISSUE THREAD

**Issue by PascalWo** [awaescher/homebridge-eltako-minisafe2#8]
**Describe The Bug:**
There seems to be a problem with the `eltako_switch` data-type.
I am using 5 Eltako-FSR14 switches for my lightbulbs.
None of them are displayed in the homebridge.
My other Eltako-FUD14 are working absolutley fine.

**To Reproduce:**
Add a Eltako-FSR14 switch to Eltako-MiniSafe-2.
It will not be dispalyed in homebridge.

**Expected behavior:**
I have already looked into the cause and found a possible solution:

Under the `cachedAccessories` file it seems like Eltako-MiniSafe-2 changed there data-type for switches.
For FUD14-Dimmers it looks like this: `"data":"eltako_dimmer"`.
For FSR14-Switches it should look like : `"data":"eltako_switch"` but is now delivered as `"data":"eltako_fsr14"`.

I guess you can just add this new data-type as a new case at `src/platform.ts`.
` case 'eltako_fsr14': {
            instance = new EltakoSwitchAccessory(this, existingAccessory);
            break;
          }`
I tried this in a local plugin modification and it worked fine.

**Configuration:**

**Screenshots:**

**Environment:**

* **Plugin Version**: v2.1.10
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v21.6.2
* **NPM Version**: 10.2.4
* **Operating System**: macOS

**Comment by awaescher** [comment]
Awesome. I don't have these devices to test. Would you create a pull request for this?

**Comment by PascalWo** [comment]
I already tried but access was denied.
Is there a problem with repo settings, or is it on my end?

> Push failed ERROR: Permission to awaescher/homebridge-eltako-minisafe2.git denied to PascalWo. Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

**Comment by awaescher** [comment]
You can't push into my repository. The workflow is to fork the repository, work there and create a pull request from your fork to my repository.
